name: Auto Commit Bot

on:
  schedule:
    - cron: "0 */5 * * *"  # Jalankan setiap 5 jam
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # Ambil semua riwayat commit

      - name: Setup Git
        run: |
          git config --global user.name "rexzea-bot"
          git config --global user.email "178272406+rexzea@users.noreply.github.com"

      - name: Paksa Sinkronisasi dengan Remote
        run: |
          git fetch --all
          git reset --hard origin/main  # Hapus semua perubahan lokal & samakan dengan remote
          git pull origin main --rebase  # Pastikan selalu up-to-date

      - name: Buat perubahan kecil (biar bisa commit)
        run: |
          echo "Terakhir update: $(date)" > update.log
          git add update.log
          git commit -m "Auto update: $(date)" || echo "Tidak ada perubahan untuk commit"

      - name: Push perubahan ke repo dengan PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push --force https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/rexzea/Simple-Hand-Tracking.git main
