name: Auto Commit Bot

on:
  schedule:
    - cron: "0 */5 * * *" 
  workflow_dispatch: 

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "rexzea-bot"
          git config --global user.email "178272406+rexzea@users.noreply.github.com"

      - name: Update timestamp
        run: |
          echo "Terakhir update: $(date)" > update.log
          git add update.log
          git commit -m "Auto update: $(date)" || echo "Tidak ada perubahan untuk commit"

      - name: Push perubahan ke repo
        run: git push
