name: Auto Commit Bot

on:
  schedule:
    - cron: "0 */5 * * *"  # Jalankan setiap 5 jam
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # Ambil semua riwayat commit

      - name: Setup Git
        run: |
          git config --global user.name "rexzea-bot"
          git config --global user.email "178272406+rexzea@users.noreply.github.com"

      - name: Buat dan checkout branch khusus
        run: |
          git checkout -b auto-commit || git checkout auto-commit
          git pull origin auto-commit --rebase || echo "Branch auto-commit baru dibuat"

      - name: Buat perubahan kecil (biar bisa commit)
        run: |
          echo "Terakhir update: $(date)" > update.log
          git add update.log
          git commit -m "Auto update: $(date)" || echo "Tidak ada perubahan untuk commit"

      - name: Push perubahan ke branch auto-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push -u origin auto-commit --force

      - name: Merge branch auto-commit ke main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main
          git pull origin main --rebase
          git merge auto-commit
          git push origin main
